---
- name: Create networks
  ovirt_network:
    data_center: "{{ item.datacenter }}"
    clusters: "{{ item.clusters }}"
    name: "{{ item.name }}"
    vlan_tag: "{{ item.vlan }}"
    vm_network: True
    state: present
  loop: "{{ vm_networks }}"

- name: Attach networks to hosts
  ovirt_host_network:
    name: "{{ item.name }}"
    interface: "{{ item.interface }}"
    networks: "{{ item.networks }}"
  loop: "{{ ovirt_hosts }}"
